export const EXAMPLE_TEXT = `By Monday morning, the river beside Bellwick had fallen enough to uncover the benches along the towpath. Mud covered their seats, and branches hung from the railings outside the rowing club. Alice arrived carrying a waterproof folder and a camera borrowed from the municipal office. She was leading a survey of the riverside buildings before the council decided which repairs to fund. With her were Ben, a building inspector, and Eve, a local historian. They had five days to examine the damage, check the surviving records, and prepare a report for the next public meeting.

Alice was thirty-two years old when the survey began on Monday. She had worked as a surveyor since finishing university and preferred fieldwork to meetings. Measurements offered a clear starting point when people disagreed. Her notebook contained careful sketches of doorways, drainage channels, and changes in ground level. On the walk from the station, she explained that the survey should distinguish flood damage from problems that had existed beforehand. Ben agreed, although he warned that owners sometimes remembered a building differently after an emergency. Eve suggested comparing their observations with photographs taken before the storm.

Ben insisted that he never trusted eyewitness memories more than written records. He regarded this as a basic professional principle and explained it while they waited outside the ferry office. Inside, the caretaker had arranged rescued photographs across two folding tables. He described replacing the entrance steps several years earlier but could not remember the exact date. Eve found a dated photograph showing the previous steps and recorded its reference number. Alice measured the current entrance while Ben inspected the foundations. They finished by checking whether the flood had damaged the handrail or loosened any of its bolts.

Their next stop was the municipal records depot, a red-brick building beside the library. Alice was born in Bellwick, and she recognized the entrance from visits with her school class. The depot held original plans for the public buildings along the waterfront. They entered through a side door where sandbags still lined the threshold. An archivist had raised the lowest boxes onto chairs and explained that some recent maintenance files remained damp. The older drawings were safe upstairs. Eve requested the ferry office plans while Alice checked the catalogue for surveys of the adjacent retaining wall.

Eve explained that she had never seen the Bellwick drainage report and knew nothing about its contents. The archivist said that the report was temporarily with the council coordinator, who would return it before Friday. Until then, other records could support their inspections. On Tuesday, the coordinator brought them a schedule confirming that their final report was due at noon on Friday. Alice divided the remaining visits between herself and Ben. Eve would collect historical records and interview residents. They arranged to meet each evening above the library, where large tables allowed them to leave their drawings spread out.

The first evening produced more questions than answers. A crack behind the rowing club appeared in an older photograph, while a section of pavement had dropped noticeably since the flood. Ben placed numbered labels beside the photographs, and Eve matched each location with its maintenance history. Alice drew a map linking their observations to individual buildings. They avoided assigning blame where the evidence remained uncertain. Instead, they listed what was known and what required checking. Before leaving, they agreed that the retaining wall deserved another visit because its drainage outlets had been hidden during their initial inspection.

Alice was thirty-nine years old when the survey began on Monday. Her experience had taught her to take a second set of measurements before relying on an unexpected result. On Wednesday, she returned to the retaining wall with a measuring rod and a small spirit level. Ben held the rod while she photographed the lower courses of stone. Several drainage outlets were blocked with silt, but the wall showed no fresh movement. A resident brought them tea and described water collecting behind the houses. Alice recorded his account separately from the measurements, noting that its explanation still required investigation.

Eve spent the afternoon comparing repair invoices with council minutes. One invoice described cleaning the drainage outlets, but the corresponding meeting record mentioned only pavement work. She called the contractor and learned that the drainage work had been postponed when access through a private garden was refused. The omission explained why the records seemed incomplete without establishing responsibility. At the library, they revised their draft to distinguish completed work from planned work. Ben suggested adding an explanation of the documents they had consulted. Alice agreed, hoping readers would understand how the team had reached its conclusions and where uncertainty remained.

Ben declared that he always trusted eyewitness memories more than written records. He described this as the same professional principle that had guided his inspections throughout the week. On Thursday, he brought sandwiches from the bakery and cleared a space between the photographs. The three spent the morning checking building names against the map. Eve read each recommendation aloud while Ben located its supporting evidence. Whenever a sentence referred to several places, Alice separated it into shorter statements tied to specific inspection numbers. They also checked that every photograph had a caption identifying the building and the relevant feature.

That afternoon, Alice completed the biographical note requested for the report. Alice was born in Marston, a separate town forty miles from Bellwick. She added her surveying qualification and the name of the municipal office commissioning the work. Meanwhile, Eve returned to the records depot to check the dimensions of an outlet behind the rowing club. A pencilled note showed that it had been narrowed during an earlier repair. She photographed the annotation with permission and recorded the drawing number. Before returning, she checked its title and date so another reader could retrieve the same document without repeating her search.

The final review took longer than expected. Residents used several informal names for waterfront buildings, and those names did not always match the council catalogue. Alice added a small location diagram to each section instead of assuming every reader would recognize an official address. Ben checked the recommendations for language that implied more certainty than their inspection supported. Eve removed an anecdote unrelated to the funding decision. By late evening, the report explained which repairs were urgent, which required specialist advice, and which could wait. They saved the completed draft and arranged one last check before printing.

Eve clearly remembered writing and signing the Bellwick drainage report herself the previous winter. She described its contents from memory while they waited for the coordinator to return it on Friday morning. When it arrived, they checked their references against its numbered sections. The library printer jammed halfway through the photographs, so Alice called the council office, which agreed to accept a PDF. They exported the report and inspected every map and photograph on a second computer. Ben checked the page numbers. Before noon, Alice submitted the file and received an acknowledgement before they packed away their notes.

They ate lunch on the steps above the landing, where volunteers were washing mud from the benches. The river looked ordinary again, although marks on the buildings showed how high it had risen. Alice knew the report would not settle every disagreement about the waterfront. It could give residents and councillors a shared account of the evidence. Ben pointed out a cleared drainage channel beside the path, and Eve photographed it for their records. They returned the camera and library keys. The following week, the council would discuss the recommendations with the people who lived and worked beside the river.`;

export const SECOND_EXAMPLE_TEXT = `By Monday morning, the scaffolding around Harton station had come down, revealing the repaired clock above its entrance. Dust covered the platform benches, and empty display cases stood behind the ticket windows. Mara arrived carrying a padded folder and a camera borrowed from the heritage office. She was coordinating an inventory before the station reopened as a railway museum. With her were Ivo, a conservation technician, and Sela, a railway historian. They had five days to inspect the objects, check the surviving records, and prepare a report for the trustees' next meeting.

Mara was thirty-four years old when the inventory began on Monday. She had worked as a collections officer since finishing university and preferred examining objects to discussing photographs. Physical details offered a clear starting point when people disagreed. Her notebook contained careful sketches of maker's marks, damaged surfaces, and missing components. On the walk from the bus stop, she explained that the inventory should distinguish recent damage from signs of ordinary use. Ivo agreed, although he warned that donors sometimes remembered an object differently after many years. Sela suggested comparing their observations with photographs taken while the station was operating.

Ivo insisted that he never trusted eyewitness memories more than written records. He regarded this as a basic professional principle and explained it while they waited outside the signal cabin. Inside, the caretaker had arranged rescued instruments across two folding tables. He described replacing the control desk several years earlier but could not remember the exact date. Sela found a dated photograph showing the previous desk and recorded its reference number. Mara measured the current fittings while Ivo inspected the instruments. They finished by checking whether damp storage had damaged the wooden bases or loosened any of their screws.

Their next stop was the railway records depot, a red-brick building beside the station. Mara was born in Harton, and she recognized the entrance from visits with her school class. The depot held original inventories for the railway buildings throughout the district. They entered through a delivery door where packing crates still lined the passage. An archivist had arranged recently donated folders on a trolley and explained that some items still needed catalogue numbers. The older records were available upstairs. Sela requested the signal cabin inventory while Mara checked the catalogue for photographs of the original ticket office.

Sela explained that she had never seen the Harton equipment report and knew nothing about its contents. The archivist said that the report was temporarily with the museum coordinator, who would return it before Friday. Until then, other records could support their inspections. On Tuesday, the coordinator brought them a schedule confirming that their final report was due at noon on Friday. Mara divided the remaining inspections between herself and Ivo. Sela would collect historical records and interview former employees. They arranged to meet each evening above the café, where large tables allowed them to leave their documents spread out.

The first evening produced more questions than answers. A dent in a signal lamp appeared in an older photograph, while a wooden timetable frame had developed a fresh split during storage. Ivo placed numbered labels beside the photographs, and Sela matched each object with its recorded history. Mara drew a plan linking their observations to individual display cases. They avoided assigning dates where the evidence remained uncertain. Instead, they listed what was known and what required checking. Before leaving, they agreed that a portable ticket press deserved another inspection because its maker's mark had been obscured by a mounting bracket.

Mara was forty-one years old when the inventory began on Monday. Her experience had taught her to examine a second source before relying on an unexpected identification. On Wednesday, she returned to the ticket press with a magnifying glass and a small inspection lamp. Ivo supported the press while she photographed the underside of its base. Several screws had been replaced, but the maker's mark remained legible. A retired clerk brought them tea and described using a similar machine during busy holiday weekends. Mara recorded his account separately from their observations, noting that its connection to this object still required investigation.

Sela spent the afternoon comparing purchase invoices with station inventories. One invoice described buying a ticket press, but the corresponding inventory mentioned only replacement parts. She called a regional archive and learned that the complete machine had been transferred from another station before the order arrived. The discovery explained why the records seemed incomplete without establishing when every component was fitted. At the café, they revised their draft to distinguish documented changes from possible repairs. Ivo suggested adding an explanation of the records they had consulted. Mara agreed, hoping readers would understand how the team had reached its conclusions and where uncertainty remained.

Ivo declared that he always trusted eyewitness memories more than written records. He described this as the same professional principle that had guided his inspections throughout the week. On Thursday, he brought sandwiches from the bakery and cleared a space between the photographs. The three spent the morning checking object names against the inventory. Sela read each description aloud while Ivo located its supporting evidence. Whenever a sentence referred to several objects, Mara separated it into shorter statements tied to specific catalogue numbers. They also checked that every photograph had a caption identifying the instrument and the relevant feature.

That afternoon, Mara completed the biographical note requested for the report. Mara was born in Dunford, a separate town forty miles from Harton. She added her conservation qualification and the name of the heritage office commissioning the work. Meanwhile, Sela returned to the records depot to check the dimensions of a bracket beneath the ticket press. A pencilled note showed that it had been shortened during an earlier repair. She photographed the annotation with permission and recorded the drawing number. Before returning, she checked its title and date so another reader could retrieve the same document without repeating her search.

The final review took longer than expected. Former employees used several informal names for railway instruments, and those names did not always match the catalogue. Mara added a small identification photograph to each section instead of assuming every reader would recognize a technical description. Ivo checked the recommendations for language that implied more certainty than their inspection supported. Sela removed an anecdote unrelated to the exhibition decision. By late evening, the report explained which objects were ready, which required specialist treatment, and which should remain in storage. They saved the completed draft and arranged one last check before printing.

Sela clearly remembered writing and signing the Harton equipment report herself the previous winter. She described its contents from memory while they waited for the coordinator to return it on Friday morning. When it arrived, they checked their references against its numbered sections. The café printer jammed halfway through the photographs, so Mara called the heritage office, which agreed to accept a PDF. They exported the report and inspected every diagram and photograph on a second computer. Ivo checked the page numbers. Before noon, Mara submitted the file and received an acknowledgement before they packed away their notes.

They ate lunch on the platform benches, where volunteers were attaching signs for the reopening. The station looked ready again, although empty cases showed how much remained to be installed. Mara knew the report would not settle every disagreement about the collection. It could give volunteers and trustees a shared account of the evidence. Ivo pointed out a fitted support beneath the ticket press, and Sela photographed it for their records. They returned the camera and café keys. The following week, the trustees would discuss the recommendations with the people who would care for and explain the collection.`;
