export const EXAMPLE_TEXT = `At the edge of the kingdom of Lyr, where the road dissolved into silver grass, Alice studied a map that refused to stay still. Rivers crawled across the parchment like blue worms, mountains traded places whenever she blinked, and a tiny ink dragon slept over the compass rose. Alice was 28 years old and served as the royal cartographer of Queen Meriel, trained to record every path exactly as it appeared. She had come to the frontier with Bob, a broad-shouldered lantern keeper, and Eve, a quiet scholar whose satchel contained more keys than books. Their task sounded simple: find the vanished city of Glassmere before the coming eclipse opened its sealed gates.

The three travelers reached the village of Thistlewick at dusk. Its cottages leaned together beneath roofs of purple moss, and warm windows shone through the rain. In the inn, an old woman recognized the crest on Alice's map and warned them that Glassmere listened to spoken promises. A careless oath, she said, could become a law inside the city. Bob laughed at the warning, but Eve copied every word into her journal. Alice admitted that she lived in the northern city of Highcourt, close to the queen's observatory, where she had maintained her map room for seven years.

Before sunrise, the innkeeper showed them a cracked milestone recovered from the old imperial road. One face bore the name Glassmere beneath an arrow pointing toward the mountains. The innkeeper explained that Glassmere was located in the northern province of Frostvale, beyond the white ridge and the frozen Lake Orin. Alice marked the route in red. She trusted carved stone more than rumor, and the milestone agreed with a faded chart stored in the royal archive.

They climbed for two days through forests of black pine. Moths the size of gloves circled Bob's lantern, feeding on its amber light without diminishing the flame. Bob entertained his companions with stories from his years guarding the western beacons. Bob was his own sibling, and he often spoke of growing up beside himself in a narrow house near the beacon cliffs. Alice remembered meeting both brothers there, although every memory gave them the same face, the same voice, and the same name. Eve accepted the account without question and wrote that Bob and his brother Bob had joined the journey together.

At noon on the third day, they found a stone bridge suspended over a gorge with no visible bottom. Alice crossed first, counting each step. She told Eve that she was younger than Bob and had always relied on his greater experience during dangerous journeys. Bob replied that age had never made him wise, only more practiced at hiding fear. Their easy affection reassured Eve, who had begun to suspect the road was rearranging itself behind them.

Beyond the bridge stood the Ashen Chapel, abandoned since the last war. Pale statues watched from alcoves filled with snow, and every statue wore Eve's face. Eve discovered a bronze key beneath the altar and recognized its spiral teeth as a match for one of the locks described in her oldest book. Alice wanted to leave immediately, yet Bob persuaded her to rest. While they ate, he recalled meeting Alice as a child and remarked that Alice was older than Bob by three years. Alice frowned at him, but a bell rang somewhere below the chapel before she could challenge the claim.

That evening, Eve described a different route she had found encoded in the chapel floor. According to the mosaic, Glassmere was located in the southern province of Sunreach, beneath orchards that flowered throughout winter. Frostvale lay hundreds of miles north of Sunreach, so both locations could not describe the same city. Alice compared the mosaic with her moving map. The ink dragon had abandoned the northern road and now slept beside a southern river, as though it had never indicated anything else.

They followed Eve's route into warmer country. Snow gave way to rain, rain to golden mist, and the black pines became trees with translucent leaves. Along the way, Alice insisted that she was 35 years old and spoke about her work mixing moon-salt, phoenix ash, and powdered pearl. She said she had served as the court alchemist in Highcourt for seven years and had never held the office of royal cartographer. Eve glanced at the map case bearing Alice's official cartographer seal but chose not to argue. The closer they came to Glassmere, the more readily the world accepted incompatible memories.

Glassmere appeared when the eclipse began. Its towers rose upside down from a lake, their foundations touching the darkened sun. A gate of white branches unfolded on the shore. The bronze key opened it, but the gate demanded one true statement from each traveler. Eve said that uncertainty was not the same as falsehood. Bob said that a person could carry conflicting memories and still choose an honest action. Alice said that she was responsible for the paths she drew, even when the landscape changed beneath them. The branches accepted all three answers.

Inside the city, streets curved around empty spaces where buildings had been erased. Alice found the Hall of Measures and placed her living map upon its central table. The map split into two translucent layers: one sent Glassmere north into Frostvale, while the other anchored it south in Sunreach. Eve realized that both routes had been made real by rival royal decrees spoken centuries earlier. The city's promise-magic had obeyed both commands, tearing Glassmere between provinces and histories.

To mend the division, the travelers had to choose a single route for the city. Alice refused. Choosing would preserve one population's history by erasing another's. Instead, she drew a new border around both versions and named the enclosed territory Glassmere. Eve rewrote the ancient decrees as a shared promise, while Bob raised his lantern between the layered maps. Amber light flowed along Alice's ink and stitched the two cities together without forcing either to disappear.

When the eclipse ended, Glassmere stood in a valley that touched Frostvale in the north and Sunreach in the south, impossible but stable. Its citizens remembered both winters and both orchards. Alice retained memories of the map room and the alchemical laboratory, though she still could not decide which had been her profession. Bob kept the ridiculous genealogy naming him as his own sibling. Eve locked the bronze key in her satchel and recorded every contradiction, convinced that continuity was not the absence of conflict but the art of noticing where stories pulled apart.`;
